### ISSUE TITLE
Can't connect v4 node and indexer

### ISSUE THREAD

**Issue by zxmns** [dydxprotocol/v4-chain#1508]
I have run v4 node and deployed local Indexer. V4 node is synced. But I see errors in the Indexer 
`
indexer-roundtable-1        | 2024-05-14 08:08:23 [error]: {
indexer-roundtable-1        |   "at": "loops-helpers/cancel_stale_orders",
indexer-roundtable-1        |   "message": "uncaught error in an individual loop",
indexer-roundtable-1        |   "error": {
indexer-roundtable-1        |     "message": "Unable to find latest block"
indexer-roundtable-1        |   },
indexer-roundtable-1        |   "taskName": "cancel_stale_orders",
indexer-roundtable-1        |   "disableGroupingHash": true,
indexer-roundtable-1        |   "timestamp": "2024-05-14T08:08:23.961Z"
indexer-roundtable-1        | }
`
As far as I understood, there are no blocks in the Indexer's database. What should I do to fix it.

**Comment by zxmns** [comment]
I did it. Just specify --indexer-kafka-conn-str when run fullnode

**Comment by xSpoooK** [comment]
Hey can you explain where you put this please ? 
I have the same error

**Comment by xSpoooK** [comment]
Could you please explain where you placed this? I’m encountering the same error.

Thanks in advance!

**Comment by zxmns** [comment]
> Could you please explain where you placed this? I’m encountering the same error.
> 
> Thanks in advance!
in command when run dydx node 
e.g. /usr/local/bin/cosmovisor run start --home=/home/user/.dydxprotocol --indexer-kafka-conn-str=localhost:9092
